apiVersion: v1
kind: Service
metadata:
  name: httpd-service-t5q1
spec:
  type: NodePort
  selector:
    app: httpd-deployment-t5q1
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30040
      