apiVersion: v1
kind: Pod
metadata:
 name: time-check
 namespace: datacenter
spec:
 containers:
  - name: time-check
    image: busybox:latest
    command: ["sh" , "-c" , "while true; do date; sleep $TIME_FREQ;done >> /opt/data/time/time-check.log"]
    env:
     - name: TIME_FREQ
       valueFrom:
        configMapKeyRef:
           name: time-config
           key: TIME_FREQ
    volumeMounts:
     - name: log-volume
       mountPath: /opt/data/time
 volumes:
  - name: log-volume
    emptyDir: {}