apiVersion: batch/v1
kind: CronJob
metadata:
  name: devops
spec:
  schedule: "*/12 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-devops
              image: nginx:latest
              command:
                - /bin/sh
                - -c
                - date; echo Welcome to xfusioncorp!.
          restartPolicy: OnFailure